### ISSUE TITLE
地区联动，不管什么省，解析出来的市只有“北京市”，而且市无法滑动。急急急！！！

### ISSUE THREAD

**Issue by XinYiWorld** [Bigkoo/Android-PickerView#228]

**Comment by XinYiWorld** [comment]
![Uploading S70329-10474657.jpg…]()

**Comment by XinYiWorld** [comment]
![Uploading S70329-10474657.jpg…]()

**Comment by xiaosong520** [comment]
@XinYiWorld setLinkage 有没有设置成false了？

**Comment by XinYiWorld** [comment]
因为崩溃所以我设置成false，否则会报outof index错误，因为市那里好像有问题，无论那个省都只显示北京市。

**Comment by xiaosong520** [comment]
@XinYiWorld 应该是第二级数据源添加出错了，请参考demo 里面 JsonDataActivity 类的代码

**Comment by XinYiWorld** [comment]
我是直接从jsondataactivity复制代码的，我现在正下载您的demo对比看。

**Comment by XinYiWorld** [comment]
目前报错如下：
                      java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
                                                                at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
                                                                at java.util.ArrayList.get(ArrayList.java:313)
                                                                at com.bigkoo.pickerview.view.WheelOptions.itemSelected(WheelOptions.java:303)
                                                                at com.bigkoo.pickerview.view.WheelOptions.setCurrentItems(WheelOptions.java:288)
                                                                at com.bigkoo.pickerview.OptionsPickerView.SetCurrentItems(OptionsPickerView.java:456)
                                                                at com.bigkoo.pickerview.OptionsPickerView.setPicker(OptionsPickerView.java:475)

**Comment by XinYiWorld** [comment]
我看了一下demo没有问题，可能我哪里搞错了，多谢大神解答啊！！！！

**Comment by XinYiWorld** [comment]
搞定了，多谢大神！

**Comment by xiaosong520** [comment]
@XinYiWorld ok， 问题解决就行

**Comment by yulinwoniu** [comment]
省市区的数据好像不全啊 只有几个省的数据
