### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3

### ISSUE THREAD

**Issue by chond** [Bigkoo/Android-PickerView#282]
05-24 15:48:24.992 32185-32185/? E/CrashReport: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                    at java.util.ArrayList.get(ArrayList.java:308)
                                                    at com.zmsoft.ccd.module.main.order.detail.fragment.OrderDetailFragment$7.onOptionsSelect(OrderDetailFragment.java:668)
                                                    at com.zmsoft.ccd.lib.widget.pickerview.OptionsPickerView.returnData(OptionsPickerView.java:503)
                                                    at com.zmsoft.ccd.lib.widget.pickerview.OptionsPickerView.onClick(OptionsPickerView.java:494)
                                                    at android.view.View.performClick(View.java:4788)
                                                    at android.view.View$PerformClick.run(View.java:19923)
                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:135)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5401)
                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
05-24 15:48:24.992 32185-32185/? E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

**Comment by xiaosong520** [comment]
@chond 滑动未停止的时候，可能因为联动数据回调还未更新就已经点击了确定导致数据不匹配。

**Comment by chond** [comment]
我只有一个滑动，当时也出现了这个问题，不过偶现，后来一直没出现过，看问题好像是index超过了总数，会不会是递归获取index的时候有问题，我最后只能临时在最外层做了index和size的判断

**Comment by xiaosong520** [comment]
@chond 你现在用的版本号是多少？

**Comment by xiaosong520** [comment]
v3.2.6 已修正
