### ISSUE TITLE
BUG省市区三级联动

### ISSUE THREAD

**Issue by chimpan** [Bigkoo/Android-PickerView#415]
一级一级快速滑动，程序奔溃，报
 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                            at com.bigkoo.pickerview.lib.WheelView.measureTextWidthHeight(WheelView.java:253)
                                                                            at com.bigkoo.pickerview.lib.WheelView.remeasure(WheelView.java:220)
                                                                            at com.bigkoo.pickerview.lib.WheelView.setAdapter(WheelView.java:329)
                                                                            at com.bigkoo.pickerview.view.WheelOptions$2.onItemSelected(WheelOptions.java:118)
                                                                            at com.bigkoo.pickerview.lib.OnItemSelectedRunnable.run(OnItemSelectedRunnable.java:12)
                                                                            at android.os.Handler.handleCallback(Handler.java:815)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:207)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by xiaosong520** [comment]
@chimpan  item的数据是否有判断null值？  如果是在数据确保无误的情况下发生的，麻烦发一下所使用的版本号。

**Comment by chimpan** [comment]
3.2.5

**Comment by NovaMagician** [comment]
我操作下也是崩溃了。

**Comment by bzy601638015** [comment]
我项目中也出现了这个情况，请问这个问题修复了吗？
