### ISSUE TITLE
感觉好像一直报这个错误！

### ISSUE THREAD

**Issue by keyescgm** [Bigkoo/Android-PickerView#428]
出错堆栈
1
java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
2
java.util.ArrayList.get(ArrayList.java:308)
3
com.bigkoo.pickerview.view.WheelOptions.getCurrentItems(WheelOptions.java:281)
4
com.bigkoo.pickerview.OptionsPickerView.returnData(OptionsPickerView.java:529)
5
com.bigkoo.pickerview.OptionsPickerView.onClick(OptionsPickerView.java:521)
6
android.view.View.performClick(View.java:4757)
7
android.view.View$PerformClick.run(View.java:19757)
8
android.os.Handler.handleCallback(Handler.java:739)
9
android.os.Handler.dispatchMessage(Handler.java:95)
10
android.os.Looper.loop(Looper.java:135)
11
android.app.ActivityThread.main(ActivityThread.java:5318)
12
java.lang.reflect.Method.invoke(Native Method)
13
java.lang.reflect.Method.invoke(Method.java:372)
14
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
15
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

**Comment by xiaosong520** [comment]
@keyescgm 这个是因为添加的一、二、三级选项数据长度不匹配导致的，建议仔细检查一下。并对null值做处理防止报空。

**Comment by keyescgm** [comment]
升级到3.2.6 之后出现的问题，之前一直没有

**Comment by keyescgm** [comment]
遇到坑了

**Comment by keyescgm** [comment]
at java.util.ArrayList.get(ArrayList.java:411)
                                                                          at com.bigkoo.pickerview.view.WheelOptions.getCurrentItems(WheelOptions.java:281)
                                                                          at com.bigkoo.pickerview.OptionsPickerView.returnData(OptionsPickerView.java:529)
                                                                          at com.bigkoo.pickerview.OptionsPickerView.onClick(OptionsPickerView.java:521)
