### ISSUE TITLE
为什么我直接使用时间选择器报错

### ISSUE THREAD

**Issue by ITskyIT** [Bigkoo/Android-PickerView#467]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setTag(java.lang.Object)' on a null object reference
                                                                             at com.bigkoo.pickerview.TimePickerView.initView(TimePickerView.java:401)
                                                                             at com.bigkoo.pickerview.TimePickerView.<init>(TimePickerView.java:119)
                                                                             at com.bigkoo.pickerview.TimePickerView$Builder.build(TimePickerView.java:381)
                                                                             at com.ruanmeng.carplace91.publish.PublishNextActivity.initTimePicker(PublishNextActivity.java:483)
                                                                             at com.ruanmeng.carplace91.publish.PublishNextActivity.onCreate(PublishNextActivity.java:182)

**Comment by xiaosong520** [comment]
@ITskyIT 这个是因为你的 Button 控件报空了导致的~

**Comment by ITskyIT** [comment]
但是我并没有引用button控件，我依赖3.2.7 复制你的demo中的代码 也是报错

**Comment by ITskyIT** [comment]
timePickerView = new TimePickerView.Builder(this, new TimePickerView.OnTimeSelectListener() {
            @Override
            public void onTimeSelect(Date date, View v) {//选中事件回调

            }
        })
                //年月日时分秒 的显示与否，不设置则默认全部显示
                .setType(new boolean[]{true, true, false, false, false, false})
                .setLabel("", "", "", "", "", "")
                .isCenterLabel(false)
                .setDividerColor(Color.DKGRAY)
                .setContentSize(21)
                .setDecorView(null)
                .build();
这段build的时候就报错了

**Comment by xiaosong520** [comment]
@ITskyIT  这个应该是你项目里面存在重复的布局，导致布局被覆盖了，控件找不到资源而出错。 试试在你自己项目里面 找找 include_pickerview_topbar.xml，看看是否有同名的布局。

**Comment by Nextweekends** [comment]
我也遇到了同样的问题 Process: cn.citytag.mapgo, PID: 23492
                                                                  java.lang.NoSuchFieldError: No field rv_topbar of type I in class Lcom/bigkoo/pickerview/R$id; or its superclasses (declaration of 'com.bigkoo.pickerview.R$id' appears in /data/app/cn.citytag.mapgo-2/base.apk:classes21.dex)
                                                                      at com.bigkoo.pickerview.TimePickerView.initView(TimePickerView.java:460)
                                                                      at com.bigkoo.pickerview.TimePickerView.<init>(TimePickerView.java:128)
                                                                      at com.bigkoo.pickerview.TimePickerView$Builder.build(TimePickerView.java:420)
