### ISSUE TITLE
省市区三级联动，同时滑动省和市两个view 方向相反，则会出现数组越界ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jiaowenzheng** [Bigkoo/Android-PickerView#574]
05-16 11:46:49.095 7111-7111/com.ontheroadstore.hs E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ontheroadstore.hs, PID: 7111
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at java.util.ArrayList.get(ArrayList.java:413)
        at com.bigkoo.pickerview.view.WheelOptions$2.onItemSelected(WheelOptions.java:136)
        at com.bigkoo.pickerview.view.WheelOptions$1.onItemSelected(WheelOptions.java:114)
        at com.contrarywind.view.WheelView$1.run(WheelView.java:344)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6252)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)

**Comment by tempersitu** [comment]
我也遇到了.省那里选到澳门就一定崩溃
