### ISSUE TITLE
点击按钮直接报这个错误，咋办？

### ISSUE THREAD

**Issue by lijingxin888** [Bigkoo/Android-PickerView#606]
java.lang.ClassCastException: com.bigkoo.pickerview.lib.WheelView cannot be cast to com.contrarywind.view.WheelView
                                                    at com.bigkoo.pickerview.view.WheelTime.setSolar(WheelTime.java:250)
                                                    at com.bigkoo.pickerview.view.WheelTime.setPicker(WheelTime.java:87)
                                                    at com.bigkoo.pickerview.view.TimePickerView.setTime(TimePickerView.java:213)
                                                    at com.bigkoo.pickerview.view.TimePickerView.initWheelTime(TimePickerView.java:131)
                                                    at com.bigkoo.pickerview.view.TimePickerView.initView(TimePickerView.java:82)
                                                    at com.bigkoo.pickerview.view.TimePickerView.<init>(TimePickerView.java:34)
                                                    at com.bigkoo.pickerview.builder.TimePickerBuilder.build(TimePickerBuilder.java:275)

**Comment by xiaosong520** [comment]
@lijingxin888 错误日志已经提示了， WheelView的路径错误，将它改成com.contrarywind.view.WheelView 即可。
