### ISSUE TITLE
数据解析内存泄漏问题以及kotlin问题

### ISSUE THREAD

**Issue by Moosphan** [Bigkoo/Android-PickerView#687]
您好，通过一下午的使用，发现以下两个问题：
1. 地址数据量较大，即使新开子线程去解析，依然发生oom问题：
```
Process: com.ucard.timeory, PID: 17372
    java.lang.OutOfMemoryError: Failed to allocate a 301989896 byte allocation with 25165824 free bytes and 109MB until OOM, max allowed footprint 178323760, growth limit 268435456
        at java.util.Arrays.copyOf(Arrays.java:3260)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:451)
        at java.lang.StringBuilder.append(StringBuilder.java:137)
        at com.ucard.timeory.ExtensionKt.getJsonFromAssets(Extension.kt:65)
        at com.ucard.timeory.mvp.address.EditAddressActivity.generateAddressData(EditAddressActivity.kt:146)
        at com.ucard.timeory.mvp.address.EditAddressActivity.access$generateAddressData(EditAddressActivity.kt:28)
        at com.ucard.timeory.mvp.address.EditAddressActivity$Companion$WithoutLeakHandler$handleMessage$1.run(EditAddressActivity.kt:50)
        at java.lang.Thread.run(Thread.java:764)
```

2. 对于kotlin的支持问题：
由于kotlin增加了对于范型的规范和控制，builder调用build方法会出现类型转换问题，无法省略类型，不知道后续能否增加对于kotlin的支持？

**Comment by xiaosong520** [comment]
@Moosphan   
第一个问题：
at java.util.Arrays.copyOf(Arrays.java:3260)
应该是拷贝导致的开销过大，业务代码可以看一下怎么去避免。

第二个问题的话，后续工作没那么忙的时候会抽空优化一下。感谢支持~

**Comment by Moosphan** [comment]
@xiaosong520 好的，加油😄
