### ISSUE TITLE
wheelview和腾讯的tuikit冲突了咋整

### ISSUE THREAD

**Issue by HuZengKan** [Bigkoo/Android-PickerView#720]
`java.lang.ClassCastException: com.tencent.qcloud.uikit.common.component.datepicker.view.WheelView cannot be cast to com.contrarywind.view.WheelView
        at com.bigkoo.pickerview.view.WheelOptions.<init>(WheelOptions.java:53)
        at com.bigkoo.pickerview.view.OptionsPickerView.initView(OptionsPickerView.java:79)
        at com.bigkoo.pickerview.view.OptionsPickerView.<init>(OptionsPickerView.java:32)
        at com.bigkoo.pickerview.builder.OptionsPickerBuilder.build(OptionsPickerBuilder.java:248)
        at com.*.InformationFragment.initPicker(InformationFragment.kt:190)
        at com.*.InformationFragment.initView(InformationFragment.kt:169)
        at com.*.InformationFragment.onActivityCreated(InformationFragment.kt:142)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2460)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`
只能把项目下下来，手动写完整引用吗？

**Comment by HuZengKan** [comment]
解决了，我把项目下载下来，做个library，然后把pickerview_options.xml和pickerview_time.xml文件名改了就完事了。
本质就是两个库的res文件重名了，然后用的是腾讯的库，导致无法强制类型转换

**Comment by KomoriWu** [comment]
对的
