### ISSUE TITLE
联动下标越界

### ISSUE THREAD

**Issue by ckdvd** [Bigkoo/Android-PickerView#806]
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.bigkoo.pickerview.view.WheelOptions$2.onItemSelected(WheelOptions.java:136)
        at com.contrarywind.view.WheelView$1.run(WheelView.java:349)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
        at dalvik.system.NativeStart.main(Native Method)

version:com.contrarywind:Android-PickerView:4.1.8

**Comment by xiaosong520** [comment]
@ckdvd  建议打印一下 position 以及数据长度，看数据是否正常。
