### ISSUE TITLE
最新版4.1.9在vivo闪退问题

### ISSUE THREAD

**Issue by OneGreenHand** [Bigkoo/Android-PickerView#828]
版本是最新版4.1.9
手机是vivo y55 android6.0
报错信息如下
  Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #8: Error inflating class Button
        at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at com.bigkoo.pickerview.view.TimePickerView.initView(TimePickerView.java:43)
        at com.bigkoo.pickerview.view.TimePickerView.<init>(TimePickerView.java:34)
        at com.bigkoo.pickerview.builder.TimePickerBuilder.build(TimePickerBuilder.java:312)
        at com.mcht.ffcp.activity.UserInfoActivity.onCreate(UserInfoActivity.java:152)
        at android.app.Activity.performCreate(Activity.java:6309)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
我换回4.1.8是不会报错的
其中(UserInfoActivity.java:152)是我初始化的时候

**Comment by OneGreenHand** [comment]
我对比了两个版本发现只加入了一个
        android:textAllCaps="false"
其他报错如下
   Caused by: java.lang.ArrayIndexOutOfBoundsException: length=20; index=1235
        at android.content.res.StringBlock.get(StringBlock.java:65)
        at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
        at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1151)
        at android.content.res.TypedArray.getString(TypedArray.java:195)
        at android.widget.TextView.<init>(TextView.java:1086)
        at android.widget.Button.<init>(Button.java:109)
        at android.widget.Button.<init>(Button.java:105)
        at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:71)
        at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:67)
        at android.support.v7.app.AppCompatViewInflater.createButton(AppCompatViewInflater.java:187)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:110)
        at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:880) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843) 
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1016) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:876) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.bigkoo.pickerview.view.TimePickerView.initView(TimePickerView.java:43) 
        at com.bigkoo.pickerview.view.TimePickerView.<init>(TimePickerView.java:34) 
        at com.bigkoo.pickerview.builder.TimePickerBuilder.build(TimePickerBuilder.java:312) 
        at com.mcht.ffcp.activity.UserInfoActivity.onCreate(UserInfoActivity.java:152) 
        at android.app.Activity.performCreate(Activity.java:6309) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1411) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by moz1q1** [comment]
AppCompatButton和Button

**Comment by yys730** [comment]
7.1魅族也同样错误
