### ISSUE TITLE
直接无法运行

### ISSUE THREAD

**Issue by Arthurshen98** [Bigkoo/Android-PickerView#839]
![image](https://user-images.githubusercontent.com/15273559/69412360-ac237500-0d49-11ea-8b63-5ac98c69bc74.png)

**Comment by Arthurshen98** [comment]
Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class pingougou.com.baseutilslib.widget.pickerview.lib.WheelView
    Caused by: java.lang.ClassNotFoundException: Didn't find class "pingougou.com.baseutilslib.widget.pickerview.lib.WheelView" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.pingougou.logistics-L9IkxpIpnVz8XkQ30NnT_Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.pingougou.logistics-L9IkxpIpnVz8XkQ30NnT_Q==/lib/arm64, /data/app/com.pingougou.logistics-L9IkxpIpnVz8XkQ30NnT_Q==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:610)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.bigkoo.pickerview.view.OptionsPickerView.initView(OptionsPickerView.java:41)
        at com.bigkoo.pickerview.view.OptionsPickerView.<init>(OptionsPickerView.java:32)
        at com.bigkoo.pickerview.builder.OptionsPickerBuilder.build(OptionsPickerBuilder.java:248)
