### ISSUE TITLE
年份能支持倒序吗

### ISSUE THREAD

**Issue by YounMan** [Bigkoo/Android-PickerView#960]
设置了startDate大于endDate，报错了，
java.lang.IllegalArgumentException: startDate can't be later than endDate
        at com.bigkoo.pickerview.view.TimePickerView.initWheelTime(TimePickerView.java:111)
        at com.bigkoo.pickerview.view.TimePickerView.initView(TimePickerView.java:82)
        at com.bigkoo.pickerview.view.TimePickerView.<init>(TimePickerView.java:34)
        at com.bigkoo.pickerview.builder.TimePickerBuilder.build(TimePickerBuilder.java:312)
是不支持吗，有没有其它配置，还是只能改源码了

**Comment by LaoXiZi** [comment]
有支持倒序的Api吗？

**Comment by hyk12345** [comment]
这个选择器不支持时间倒序么？
