### ISSUE TITLE
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again

### ISSUE THREAD

**Issue by 1025342523** [Bigkoo/Android-PickerView#966]
--------- beginning of crash

02-01 17:53:42.451 10893 10893 E AndroidRuntime: FATAL EXCEPTION: main

02-01 17:53:42.451 10893 10893 E AndroidRuntime: Process: com.xrd.chuyi, PID: 10893

02-01 17:53:42.451 10893 10893 E AndroidRuntime: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at java.lang.Thread.nativeCreate(Native Method)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at java.lang.Thread.start(Thread.java:1063)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1556)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:310)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:591)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Executors.java:654)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at com.contrarywind.view.WheelView.scrollBy(WheelView.java:275)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at com.contrarywind.listener.LoopViewGestureListener.onFling(LoopViewGestureListener.java:22)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:650)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at com.contrarywind.view.WheelView.onTouchEvent(WheelView.java:672)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9300)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2771)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at me.yokeyword.fragmentation.SupportActivity.dispatchTouchEvent(SupportActivity.java:59)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at com.xrd.chuyi.base.activity.BaseActivity.dispatchTouchEvent(BaseActivity.java:355)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9520)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)

02-01 17:53:42.451 10893 10893 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135

**Comment by 1025342523** [comment]
创建的线程太多，导致内存溢出，有没有方法解决，各位大佬？
